### ISSUE TITLE
there is no reactor running

### ISSUE THREAD

**Issue by 89z** [ATiltedTree/ytextract#25]
If I try this program:

~~~rs
#[async_std::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
   let client = ytextract::Client::new().await?;
   let video = client.video("nI2e-J6fsuk".parse()?).await?;
   println!("Title: {}", video.title());
   Ok(())
}
~~~

I get this result:

~~~
thread 'main' panicked at 'there is no reactor running, must be called from the
context of a Tokio 1.x runtime',
C:\Users\Steven\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.8.1\src\runtime\blocking\pool.rs:84:33
~~~

**Comment by ATiltedTree** [comment]
You need to enable the `tokio1` feature of `async-std`:
```toml
[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
```
